name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Check
        run: pnpm check

      - name: Test
        run: pnpm test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          update-command: 'true'

      - name: Print Output
        id: output
        run: echo "updated=${{ steps.test-action.outputs.updated }}"
